name: transport_tracker
description: An offline-first mobile app to track passengers, trips, and billing.
publish_to: 'none' # Prevent accidental publishing to pub.dev

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1 # Latest stable version as of 2025【554906261333601†L35-L40】
  hive: ^2.2.3 # Latest stable hive【765138222112134†L70-L74】
  hive_flutter: ^1.1.0
  uuid: ^4.4.0
  intl: ^0.19.0
  speech_to_text: ^6.6.2 # Compatible version for Flutter 3.22.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
